config/routes.rb
Rails.application.routes.draw do
  resources :wallpapers do 
  	resources :comments
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'wallpapers#index'

  get 'about', to: 'wallpapers#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :wallpaper
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :wallpapers

  validates :email, presence: true 
  validates_associated :wallpapers
  validates :email, uniqueness: true         
end

app/models/wallpaper.rb
class Wallpaper < ApplicationRecord

	belongs_to :user

    has_many :comments, dependent: :destroy
	validates :title, :content, :user_id, presence: true

    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@wallpaper = Wallpaper.find(params[:wallpaper_id])
		@comment = @wallpaper.comments.create(params[:comment].permit(:name, :body))
		redirect_to wallpaper_path(@wallpaper)
	end 

	def destroy
		@wallpaper = Wallpaper.find(params[:wallpaper_id])
		@comments = @wallpaper.comments.find(params[:id])
		@comments.destroy
		redirect_to wallpaper_path(@wallpaper)
	end	
end

app/controllers/wallpapers_controller.rb
class WallpapersController < ApplicationController
  before_action :set_wallpaper, only: [:show, :edit, :update, :destroy]

  # GET /wallpapers
  # GET /wallpapers.json
  def index
    @wallpapers = Wallpaper.paginate(:page => params[:page], :per_page => 2)
  end

  # GET /wallpapers/1
  # GET /wallpapers/1.json
  def show
  end

  # GET /wallpapers/new
  def new
    @wallpaper = Wallpaper.new
  end

  # GET /wallpapers/1/edit
  def edit
  end

  # POST /wallpapers
  # POST /wallpapers.json
  def create
    @wallpaper = current_user.wallpapers.new(wallpaper_params)

    respond_to do |format|
      if @wallpaper.save
        format.html { redirect_to @wallpaper, notice: 'Wallpaper was successfully created.' }
        format.json { render :show, status: :created, location: @wallpaper }
      else
        format.html { render :new }
        format.json { render json: @wallpaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallpapers/1
  # PATCH/PUT /wallpapers/1.json
  def update
    respond_to do |format|
      if @wallpaper.update(wallpaper_params)
        format.html { redirect_to @wallpaper, notice: 'Wallpaper was successfully updated.' }
        format.json { render :show, status: :ok, location: @wallpaper }
      else
        format.html { render :edit }
        format.json { render json: @wallpaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallpapers/1
  # DELETE /wallpapers/1.json
  def destroy
    @wallpaper.destroy
    respond_to do |format|
      format.html { redirect_to wallpapers_url, notice: 'Wallpaper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallpaper
      @wallpaper = Wallpaper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wallpaper_params
      params.require(:wallpaper).permit(:title, :content, :user_id, :avatar)
    end
    
    def about
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/wallpapers_helper.rb
module WallpapersHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.name %></p>
<p><%= comment.body %></p>
<p><%= time_ago_in_words(comment.created_at) %></p>

<p> <%= link_to 'Delete', [comment.wallpaper,comment], method: :delete, data: { confirm: 'Are you sure?'} %></p>

app/views/comments/_form.html.erb
<%= form_for([@wallpaper,@wallpaper.comments.build]) do |f| %>
<p>
	<%= f.label :name %>
	<%= f.text_field :name %>
</p> 
<p>
	<%= f.label :body %>
	<%= f.text_area :body %>
</p>
<br>
<p>
	<%=  f.submit %>
</p>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mywallpaperssite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= link_to 'About', about_path %>
      <%= link_to 'Home', root_path %>
    </p>
    <p>
      <% if user_signed_in? %>
      <li>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
      </li>
      <li>
        <%= link_to "Edit registration", edit_user_registration_path %>
      </li>
      <% else %>
      <li>
        <%= link_to "Sign up", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "Log in", new_user_session_path %>
      </li>
    </p>
    <% end %>
    <%= yield %>
  
  </body>
</html>

app/views/wallpapers/_form.html.erb
<%= form_with(model: wallpaper, local: true) do |form| %>
  <% if wallpaper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallpaper.errors.count, "error") %> prohibited this wallpaper from being saved:</h2>

      <ul>
      <% wallpaper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
     
     <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wallpapers/about.html.erb
<h1>About Wallpaper Blog</h1>
<%= link_to 'Home', root_path %>

app/views/wallpapers/edit.html.erb
<h1>Editing Wallpaper</h1>

<%= render 'form', wallpaper: @wallpaper %>

<%= link_to 'Show', @wallpaper %> |
<%= link_to 'Back', wallpapers_path %>

app/views/wallpapers/index.html.erb
<p id="notice"><%= notice %></p>

<hr>
  <tbody>
    <% @wallpapers.each do |wallpaper| %>
         <p><%= image_tag wallpaper.avatar.url(:thumb)%></p>      
        <p><h3><%= wallpaper.title %></h3></p>
        <div class= "conteiner "> <%= wallpaper.content %></div>
        <h5>Author: <%= wallpaper.user.email %></h5>
        <% if user_signed_in? %>
        <p>
        <%= link_to 'Show', wallpaper %>
        <%= link_to 'Edit', edit_wallpaper_path(wallpaper) %>
        <%= link_to 'Destroy', wallpaper, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
        <% end %>
    <% end %>
  </tbody>
</table>


<br>
<br>

<% if user_signed_in? %> 

<%= link_to 'New Wallpaper', new_wallpaper_path %>
<hr>

<% end %>
<%= will_paginate @wallpapers %>

app/views/wallpapers/new.html.erb
<h1>New Wallpaper</h1>

<%= render 'form', wallpaper: @wallpaper %>

<%= link_to 'Back', wallpapers_path %>

app/views/wallpapers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><strong>Wallpaper:</strong></h2>	
  <%= image_tag @wallpaper.avatar.url %>
</p>


<p>
  <strong>Title:</strong>
  <%= @wallpaper.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @wallpaper.user.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @wallpaper.content %>
</p>
<br>
<h2><%= @wallpaper.comments.count %></h2>
    <%= render @wallpaper.comments %>
    <h3>Add Comment: </h3>
    <%= render 'comments/form' %>
<br>

<%= link_to 'Edit', edit_wallpaper_path(@wallpaper) %> |
<%= link_to 'Back', wallpapers_path %>